version: '3.7'

services:

  mongo:
    image: mongo
    container_name: vebio_mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: vebio_db
      MONGO_INITDB_ROOT_USERNAME: vebio_user
      MONGO_INITDB_ROOT_PASSWORD: vebio_password
