# Generated by Django 2.2.12 on 2020-04-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biometric',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(verbose_name='creation date')),
                ('image_name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=256)),
                ('lower_thresh', models.IntegerField()),
                ('upper_thresh', models.IntegerField()),
                ('denoise_lvl', models.IntegerField()),
                ('clahe_lvl', models.IntegerField()),
                ('preprocessed_url', models.CharField(max_length=256)),
                ('gauss_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LoadedImage',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='date added')),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
